#!/usr/bin/env python

import json
import libvirt
import sys
import time
import argparse
import io
import cv2
import pytesseract
from io import StringIO
from io import BytesIO
from PIL import Image
from libsixel.encoder import Encoder,SIXEL_OPTFLAG_WIDTH, SIXEL_OPTFLAG_COLORS

# functions

def saver(stream, data, file_handle):
    """Callback helper to write incoming stream chunks directly to a file."""
    return file_handle.write(data)
#    return len(data)



# Main code

# parse arguments
parser = argparse.ArgumentParser(
prog="vmshot",
description="Virtual machine screenshot"
)

parser.add_argument("--server", help="Libvirt Server URI")
parser.add_argument("--vm", help="Libvirt Server URI")
parser.add_argument("--outputfile", help="Save screenshot in file", default='')
parser.add_argument("--sixel", help="Render screenshot in terminal via sixel",action='store_true')
parser.add_argument("--ocr", help="Extract text from screenshot with Tesseract",action='store_true')
parser.add_argument("--ocr-psm", help="Page segmentation mode",default='')
parser.add_argument("--ocr-whitelist", help="Allowed characters list",default='')

args = parser.parse_args()

if not(args.server):
    print (' e : Server URI is not provided')
    exit();

if not(args.vm):
    print (' e : Virtual Machine name is not provided')
    exit();


# connect to libvirt server
conn = libvirt.open(args.server)
# find VM
dom = conn.lookupByName(args.vm)

stream = conn.newStream()

mime_type = dom.screenshot(stream, 0, 0)
#print(f"Detected format MIME-type: {mime_type}")

if args.outputfile:
    with open(args.outputfile, "wb") as f:
            # recvAll handles the streaming loop under the hood via the callback
            stream.recvAll(saver, f)
            exit()

#init stream to use as file
inputf = BytesIO()
#get data from connection stream and save in stream used as file
stream.recvAll(saver, inputf)
#close connection stream
ret = stream.finish()
#rewind stream used as file
inputf.seek(0)

#open stream used as file as image
im = Image.open(inputf)
#create oher stream used as file
outputf = BytesIO()
#save image to other stream as file
im.save(outputf,format="PNG")
#contents = outputf.getvalue()

#create temporary file
with open(args.vm+'.png', "wb") as f:
    #save other stream data in it
    f.write(outputf.getbuffer())
    #outputf.write(saver, f)

if args.sixel:
    #init sixel encoder
    encoder = Encoder()
    #encoder.setopt(SIXEL_OPTFLAG_WIDTH, "300")   # Resize width to 300 pixels
    #encoder.setopt(SIXEL_OPTFLAG_COLORS, "16")
    #encoder.encode('1.png')
    #render sixel image (in current terminal)
    encoder.encode(args.vm+'.png')

if args.ocr:
    custom_config=''
    if args.ocr_psm:
        custom_config+=' --psm '+args.ocr_psm
    if args.ocr_whitelist:
        custom_config+=" -c tessedit_char_whitelist=\""+args.ocr_whitelist+"\""
    gray=cv2.cvtColor(cv2.imread(args.vm+'.png'), cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray, config=custom_config, lang='eng')
    print(text)
